kind: pipeline
name: default

steps:
  - name: run-api-starter-tests
    image: docker/compose:1.24.1
    commands:
      - ./bin/test.sh
    when:
      status:
        - failure
        - success
      event:
        - pull_request
      branch:
        - master
        - "*:master"
